# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: 'daily'
      groups:
        production-updates:
          applies-to: version-updates
          dependency-type: production
          update-types: [minor, patch]
        dev-updates:
          applies-to: version-updates
          dependency-type: development
          update-types: [minor, patch]
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
