name: Basic Setup
description: Install Bun and dependencies

inputs:
  install:
    default: 'true'
    description: Whether or not to run 'bun install'

runs:
  using: composite

  steps:
    - name: 🛠️ Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version-file: '.tool-versions'

    - uses: voidzero-dev/setup-vp@v1
      with:
        node-version-file: .node-version
        cache: true

    - name: 📦 Install Dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      env:
        INSTALL_ARGS: ${{ inputs.installArgs }}
      run: vp install --frozen-lockfile $INSTALL_ARGS
