name: Basic Setup
description: Install Bun and dependencies

inputs:
  install:
    default: 'true'
    description: Whether or not to run 'bun install'

runs:
  using: composite

  steps:
    - name: 🛠️ Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version-file: '.tool-versions'

    - name: 🔍 Get Bun cache path
      if: ${{ inputs.install == 'true' }}
      id: bun-cache
      shell: bash
      run: echo "path=$(bun pm cache)" >> $GITHUB_OUTPUT

    - name: 📦 Cache Bun store
      if: ${{ inputs.install == 'true' }}
      uses: actions/cache@v4
      with:
        path: ${{ steps.bun-cache.outputs.path }}
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}

    - name: 📦 Cache buildc
      if: ${{ inputs.install == 'true' }}
      uses: actions/cache@v4
      with:
        path: .cache/packages
        key: ${{ runner.os }}-buildc-${{ hashFiles('bun.lock') }}

    - name: 📦 Install Dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: bun ci ${{ inputs.installArgs }}
