name: Basic Setup
description: Install Bun and Dependencies

inputs:
  install:
    default: 'true'
    type: boolean
    description: Whether or not to run 'bun install'

  installArgs:
    default: ''
    type: string
    description: Additional args to append to "bun install"

runs:
  using: composite

  steps:
    - name: 🛠️ Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: 📦 Install Dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: bun install ${{ inputs.installArgs }}
