name: Basic Setup
description: Install Bun and dependencies

inputs:
  install:
    default: 'true'
    description: Whether or not to run 'bun install'

runs:
  using: composite

  steps:
    - name: 🛠️ Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version-file: '.tool-versions'

    - name: 📦 Cache Dependencies
      if: ${{ inputs.install == 'true' }}
      id: cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          node_modules
          packages/*/node_modules
          packages/*/.wxt
          .cache/packages
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}

    - name: 📦 Install Dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: bun ci ${{ inputs.installArgs }}
