packages:
  - docs
  - packages/*

catalog:
  '@aklinker1/check': ^1.4.5
  '@faker-js/faker': ^9.2.0
  '@types/chrome': ^0.0.280
  '@types/fs-extra': ^11.0.4
  '@types/lodash.merge': ^4.6.9
  '@types/node': ^20.17.6
  '@types/normalize-path': ^3.0.2
  '@types/prompts': ^2.4.9
  '@types/react': ^19.0.1
  '@types/react-dom': ^19.0.2
  '@webext-core/fake-browser': ^1.3.1
  extract-zip: ^2.0.1
  happy-dom: ^15.11.4
  lodash.merge: ^4.6.2
  oxlint: ^0.11.1
  publint: ^0.2.12
  react-dom: ^19.0.0
  react: ^19.0.0
  sass: ^1.80.7
  solid-js: ^1.9.4
  tsx: 4.15.7
  typescript: ^5.6.3
  unbuild: ^2.0.0
  unocss: ^0.64.0
  vitest-plugin-random-seed: ^1.1.0
  vitest: ^2.1.4
