packages:
  - docs
  - packages/*
catalog:
  '@1natsu/wait-element': ^4.1.2
  '@aklinker1/buildc': ^1.1.4
  '@aklinker1/check': ^1.4.5
  '@aklinker1/rollup-plugin-visualizer': 5.12.0
  '@commitlint/config-conventional': ^19.7.1
  '@commitlint/types': ^19.5.0
  '@faker-js/faker': ^9.2.0
  '@sveltejs/vite-plugin-svelte': ^4.0.0 || ^5.0.0
  '@types/chrome': ^0.0.280
  '@types/fs-extra': ^11.0.4
  '@types/lodash.merge': ^4.6.9
  '@types/node': ^20.17.6
  '@types/normalize-path': ^3.0.2
  '@types/prompts': ^2.4.9
  '@types/react': ^19.0.1
  '@types/react-dom': ^19.0.2
  '@types/webextension-polyfill': ^0.12.1
  '@vitejs/plugin-react': ^4.3.4
  '@vitejs/plugin-vue': ^5.2.0
  '@vitest/coverage-v8': ^2.1.4
  '@webext-core/fake-browser': ^1.3.1
  '@webext-core/isolated-element': ^1.1.2
  '@webext-core/match-patterns': ^1.0.3
  async-mutex: ^0.5.0
  c12: ^1.11.2
  cac: ^6.7.14
  changelogen: ^0.5.7
  chokidar: ^4.0.3
  ci-info: ^4.1.0
  confbox: ^0.1.8
  consola: ^3.2.3
  defu: ^6.1.4
  dequal: ^2.0.3
  dotenv: ^16.4.5
  dotenv-expand: ^12.0.1
  esbuild: ^0.21.5
  extract-zip: ^2.0.1
  fast-glob: ^3.3.2
  filesize: ^10.1.6
  fs-extra: ^11.2.0
  get-port-please: ^3.1.2
  giget: ^1.2.3
  happy-dom: ^15.11.4
  hookable: ^5.5.3
  import-meta-resolve: ^4.1.0
  is-wsl: ^3.1.0
  jiti: ^1.21.6
  json5: ^2.2.3
  jszip: ^3.10.1
  linkedom: ^0.18.5
  lint-staged: ^15.2.10
  lodash.merge: ^4.6.2
  magicast: ^0.3.5
  markdown-it-footnote: ^4.0.0
  minimatch: ^10.0.1
  nano-spawn: ^0.2.0
  normalize-path: ^3.0.0
  nypm: ^0.3.12
  ohash: ^1.1.4
  open: ^10.1.0
  ora: ^8.1.1
  oxlint: ^0.11.1
  perfect-debounce: ^1.0.0
  picocolors: ^1.1.1
  prettier: ^3.3.3
  prompts: ^2.4.2
  publint: ^0.2.12
  publish-browser-extension: ^2.3.0 || ^3.0.0
  react: ^19.0.0
  react-dom: ^19.0.0
  sass: ^1.80.7
  scule: ^1.3.0
  sharp: ^0.33.5
  simple-git-hooks: ^2.11.1
  solid-js: ^1.9.4
  tsx: 4.15.7
  typedoc: ^0.25.4
  typedoc-plugin-frontmatter: ^1.1.0
  typedoc-plugin-markdown: 4.0.0-next.23
  typedoc-vitepress-theme: 1.0.0-next.3
  typescript: ^5.6.3
  unbuild: ^2.0.0
  unimport: ^3.13.1
  unocss: ^0.64.0
  vite: ^5.0.0 || <=6.0.8
  vite-node: ^2.1.4 || ^3.0.0
  vite-plugin-solid: ^2.11.6
  vitepress: ^1.5.0
  vitepress-knowledge: ^0.4.0
  vitest: ^2.1.4
  vitest-mock-extended: ^2.0.2
  vitest-plugin-random-seed: ^1.1.0
  vue: ^3.5.12
  web-ext-run: ^0.2.1
  webextension-polyfill: ^0.12.0
