import { addViteConfig, defineWxtModule } from '../modules';
import type {
  EslintGlobalsPropValue,
  ResolvedEslintrc,
  ResolvedEslintrcLegacy,
  Wxt,
  WxtDirFileEntry,
  WxtModule,
} from '../types';
import { type Unimport, createUnimport, toExports } from 'unimport';
import UnimportPlugin from 'unimport/unplugin';

export default defineWxtModule({
  name: 'wxt:built-in:unimport',
  setup(wxt) {
    let unimport: Unimport;
    const isEnabled = () => !wxt.config.imports.disabled;

    // Add user module imports to config
    wxt.hooks.hook('config:resolved', () => {
      const addModuleImports = (module: WxtModule<any>) => {
        if (!module.imports) return;

        wxt.config.imports.imports ??= [];
        wxt.config.imports.imports.push(...module.imports);
      };

      wxt.config.builtinModules.forEach(addModuleImports);
      wxt.config.userModules.forEach(addModuleImports);
    });

    // Create unimport instance AFTER "config:resolved" so any modifications to the
    // config inside "config:resolved" are applied.
    wxt.hooks.afterEach((event) => {
      if (event.name === 'config:resolved') {
        unimport = createUnimport(wxt.config.imports);
      }
    });

    // Generate types
    wxt.hooks.hook('prepare:types', async (_, entries) => {
      // Update cache before each rebuild
      await unimport.init();

      // Always generate the #import module types
      entries.push(await getImportsModuleEntry(wxt, unimport));

      if (!isEnabled()) return;

      // Only create global types when user has enabled auto-imports
      entries.push(await getImportsDeclarationEntry(unimport));

      if (!wxt.config.imports.eslintrc) return;

      // Only generate ESLint config if that feature is enabled
      const eslintConfigEntries = await getEslintConfigEntries(
        unimport,
        wxt.config.imports.eslintrc,
      );

      entries.push(...eslintConfigEntries);
    });

    // Add vite plugin
    addViteConfig(wxt, () => ({
      plugins: [UnimportPlugin.vite(wxt.config.imports)],
    }));
  },
});

async function getImportsDeclarationEntry(
  unimport: Unimport,
): Promise<WxtDirFileEntry> {
  return {
    path: 'types/imports.d.ts',
    text: [
      '// Generated by wxt',
      await unimport.generateTypeDeclarations(),
      '',
    ].join('\n'),
    tsReference: true,
  };
}

async function getImportsModuleEntry(
  wxt: Wxt,
  unimport: Unimport,
): Promise<WxtDirFileEntry> {
  const imports = await unimport.getImports();
  return {
    path: 'types/imports-module.d.ts',
    text: [
      '// Generated by wxt',
      '// Types for the #import virtual module',
      "declare module '#imports' {",
      `  ${toExports(imports, wxt.config.wxtDir, true).replaceAll('\n', '\n  ')}`,
      '}',
      '',
    ].join('\n'),
    tsReference: true,
  };
}

async function getEslintConfigEntries(
  unimport: Unimport,
  eslintrc: ResolvedEslintrc | ResolvedEslintrcLegacy,
): Promise<WxtDirFileEntry[]> {
  const globals = (await unimport.getImports())
    .map((i) => i.as ?? i.name)
    .filter(Boolean)
    .sort()
    .reduce<Record<string, EslintGlobalsPropValue>>((globals, name) => {
      globals[name] = eslintrc.globalsPropValue;
      return globals;
    }, {});

  if (eslintrc.legacy) {
    return [getEslintLegacyConfigEntry(eslintrc, globals)];
  } else {
    return getEslintConfigEntry(eslintrc, globals);
  }
}

export function getEslintLegacyConfigEntry(
  eslintrc: ResolvedEslintrcLegacy,
  globals: Record<string, EslintGlobalsPropValue>,
): WxtDirFileEntry {
  return {
    path: eslintrc.filePath,
    text: JSON.stringify({ globals }, null, 2) + '\n',
  };
}

export function getEslintConfigEntry(
  eslintrc: ResolvedEslintrc,
  globals: Record<string, EslintGlobalsPropValue>,
): WxtDirFileEntry[] {
  const jsFileEntry: WxtDirFileEntry = {
    path: eslintrc.filePath,
    text: `const globals = ${JSON.stringify(globals, null, 2)}

export default {
  name: "wxt/auto-imports",
  languageOptions: {
    globals,
    /** @type {import('eslint').Linter.SourceType} */
    sourceType: "module",
  },
};
`,
  };

  const tsFileEntry: WxtDirFileEntry = {
    path: eslintrc.definitionPath,
    text: `import type { ConfigObject } from "@eslint/core";
declare const config: ConfigObject;
export default config;
`,
  };

  return [jsFileEntry, tsFileEntry];
}
