import { addViteConfig, defineWxtModule } from '~/modules';
import type {
  EslintGlobalsPropValue,
  Wxt,
  WxtDirFileEntry,
  WxtModule,
  WxtResolvedUnimportOptions,
} from '~/types';
import { type Unimport, createUnimport } from 'unimport';
import { Plugin } from 'vite';
import { extname } from 'node:path';

export default defineWxtModule({
  name: 'wxt-builtin:unimport',
  setup(wxt) {
    const options = wxt.config.imports;
    if (options === false) return;

    let unimport: Unimport;

    // Add user module imports to config
    wxt.hooks.hook('ready', () => {
      const addModuleImports = (module: WxtModule<any>) => {
        if (!module.imports) return;

        options.imports ??= [];
        options.imports.push(...module.imports);
      };

      wxt.config.builtinModules.forEach(addModuleImports);
      wxt.config.userModules.forEach(addModuleImports);
    });

    // Create unimport instance after READY so any modifications to the config
    // inside "ready" are applied.
    wxt.hooks.afterEach((event) => {
      if (event.name === 'ready') {
        unimport = createUnimport(options);
      }
    });

    // Generate types
    wxt.hooks.hook('prepare:types', async (wxt, entries) => {
      entries.push(await getImportsDeclarationEntry(wxt, unimport));

      if (!options.eslintrc.enabled) return;
      entries.push(await getImportsEslintEntry(unimport, options));
    });

    // Add vite plugin
    addViteConfig(wxt, () => ({
      plugins: [vitePlugin(unimport)],
    }));
  },
});

export function vitePlugin(unimport: Unimport): Plugin {
  const ENABLED_EXTENSIONS = new Set([
    '.js',
    '.jsx',
    '.ts',
    '.tsx',
    '.vue',
    '.svelte',
  ]);
  return {
    name: 'wxt:unimport',
    async transform(code, id) {
      // Don't transform dependencies
      if (id.includes('node_modules')) return;

      // Don't transform non-js files
      if (!ENABLED_EXTENSIONS.has(extname(id))) return;

      const injected = await unimport.injectImports(code, id);
      return {
        code: injected.code,
        map: injected.s.generateMap({ hires: 'boundary', source: id }),
      };
    },
  };
}

async function getImportsDeclarationEntry(
  wxt: Wxt,
  unimport: Unimport,
): Promise<WxtDirFileEntry> {
  // Load project imports into unimport memory so they are output via generateTypeDeclarations
  await unimport.scanImportsFromDir(undefined, { cwd: wxt.config.srcDir });

  return {
    path: 'types/imports.d.ts',
    text: [
      '// Generated by wxt',
      await unimport.generateTypeDeclarations(),
      '',
    ].join('\n'),
    tsReference: true,
  };
}

async function getImportsEslintEntry(
  unimport: Unimport,
  options: WxtResolvedUnimportOptions,
): Promise<WxtDirFileEntry> {
  const globals: Record<string, EslintGlobalsPropValue> = {};
  const eslintrc = { globals };

  (await unimport.getImports())
    .map((i) => i.as ?? i.name)
    .filter(Boolean)
    .sort()
    .forEach((name) => {
      eslintrc.globals[name] = options.eslintrc.globalsPropValue;
    });

  return {
    path: options.eslintrc.filePath,
    text: JSON.stringify(eslintrc, null, 2) + '\n',
  };
}
