#!/bin/bash

#
# Generate code in README.md and sync it with wxt/packages/README.md for NPM
#

bunx automd
echo "<!-- DO NOT EDIT, THIS FILE WAS GENERATED BY '../../scripts/generate-readmes.sh' -->" > packages/wxt/README.md
cat README.md >> packages/wxt/README.md
