import type { Entrypoint } from 'wxt';
import { getEntrypointBundlePath } from 'wxt';

/**
 * Build-time helpers for `@wxt-dev/entrypoint-refs`. Not part of the public API
 * — kept here so the unit tests can exercise them in isolation. Anything
 * exported from this file is bundled into `dist/index.mjs` but reachable only
 * to code inside this package.
 */

export function refToConstName(ref: string): string {
  return (
    'ENTRYPOINT_' +
    ref
      .toUpperCase()
      .replace(/[^A-Z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '')
  );
}

export function getBundleExt(entry: Entrypoint): '.html' | '.css' | '.js' {
  switch (entry.type) {
    case 'sandbox':
    case 'bookmarks':
    case 'history':
    case 'newtab':
    case 'devtools':
    case 'unlisted-page':
    case 'popup':
    case 'options':
    case 'sidepanel':
      return '.html';
    case 'content-script-style':
    case 'unlisted-style':
      return '.css';
    default:
      return '.js';
  }
}

export function getRef(entry: Entrypoint): string {
  return entry.options.ref || entry.name;
}

export function buildEntrypointsFile(
  entrypoints: Entrypoint[],
  outDir: string,
): string {
  const lines = ['// Generated by @wxt-dev/entrypoint-refs', ''];

  const cssNames = new Set(
    entrypoints
      .filter((e) => e.type === 'content-script-style')
      .map((e) => e.name),
  );

  const seen = new Set<string>();
  for (const entry of entrypoints) {
    const ref = getRef(entry);
    let constName = refToConstName(ref);
    let suffix = 2;
    while (seen.has(constName)) {
      constName = refToConstName(`${ref}_${suffix++}`);
    }
    seen.add(constName);

    const path = getEntrypointBundlePath(entry, outDir, getBundleExt(entry));
    lines.push(`export const ${constName} = ${JSON.stringify(path)};`);

    if (entry.type === 'content-script' && cssNames.has(entry.name)) {
      const cssRef = `${ref}_css`;
      let cssConstName = refToConstName(cssRef);
      let cssSuffix = 2;
      while (seen.has(cssConstName)) {
        cssConstName = refToConstName(`${cssRef}_${cssSuffix++}`);
      }
      seen.add(cssConstName);
      const cssPath = getEntrypointBundlePath(entry, outDir, '.css');
      lines.push(`export const ${cssConstName} = ${JSON.stringify(cssPath)};`);
    }
  }

  lines.push('');
  return lines.join('\n');
}
